=== hfrebort/certificate/certificate-backend/src/main/resources/ExcelToCertsDB.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
	targetNamespace="http://www.ofi.at/ExcelToCertsDB"
	xmlns:tns="http://www.ofi.at/ExcelToCertsDB"
	attributeFormDefault="unqualified" 
	elementFormDefault="qualified">

	<xs:complexType name="ColumnMappingType">
		<xs:attribute name="excelColumn">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:pattern value="[A-Z]{1,3}"></xs:pattern>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="type">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="date"></xs:enumeration>
					<xs:enumeration value="int"></xs:enumeration>
					<xs:enumeration value="char"></xs:enumeration>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="databaseColumn" type="xs:string"></xs:attribute>
	</xs:complexType>

    <xs:complexType name="CertificateSheet">
	   	<xs:sequence>
	   		<xs:element name="columnMapping" type="tns:ColumnMappingType" maxOccurs="unbounded" />
	   	</xs:sequence>
	   	
        <xs:attribute name="sheetName" type="xs:string"></xs:attribute>
    </xs:complexType>
    
    <xs:element name="certificateSheet" type="tns:CertificateSheet"></xs:element>
</xs:schema>

=== hfrebort/certificate/certificate-backend/src/main/resources/ExcelToCertsDB.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<certificateSheet 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:noNamespaceSchemaLocation="./ExcelToCertsDB.xsd" 
	sheetName="Auditprogramm - Gültige Zert">
	<columnMapping excelColumn="B"  type="date" databaseColumn="finished" />
	<columnMapping excelColumn="C"  type="date" databaseColumn="vb1" />
	<columnMapping excelColumn="D"  type="date" databaseColumn="vb2" /> 					
	<columnMapping excelColumn="E"  type="date" databaseColumn="vb3" /> 					
	<columnMapping excelColumn="F"  type="date" databaseColumn="vb4" /> 					
	<columnMapping excelColumn="G"  type="date" databaseColumn="manufacturer" />
	<columnMapping excelColumn="H"  type="date" databaseColumn="manufacturerContact" /> 	
	<columnMapping excelColumn="I"  type="char" databaseColumn="manufacturerLocation" /> 	
	<columnMapping excelColumn="J"  type="char" databaseColumn="productDescription" /> 	
	<columnMapping excelColumn="K"  type="char" databaseColumn="auditMonthLatest" /> 		
	<columnMapping excelColumn="L"  type="char" databaseColumn="checkedBy" /> 			
	<columnMapping excelColumn="M"  type="date" databaseColumn="auditor" /> 					
	<columnMapping excelColumn="N"  type="char" databaseColumn="checkOf" /> 				
	<columnMapping excelColumn="O"  type="char" databaseColumn="probeTaken" /> 			
	<columnMapping excelColumn="P"  type="char" databaseColumn="AoC" /> 					
	<columnMapping excelColumn="Q"  type="char" databaseColumn="n1" />  					
	<columnMapping excelColumn="R"  type="int"  databaseColumn="n2" />  					
	<columnMapping excelColumn="S"  type="char" databaseColumn="n3" />  					
	<columnMapping excelColumn="T"  type="char" databaseColumn="n4" />  					
	<columnMapping excelColumn="U"  type="char" databaseColumn="n5" />  					
	<columnMapping excelColumn="V"  type="char" databaseColumn="n6" />  					
	<columnMapping excelColumn="W"  type="char" databaseColumn="n7" />  					
	<columnMapping excelColumn="X"  type="char" databaseColumn="n8" />  					
	<columnMapping excelColumn="Y"  type="char" databaseColumn="n9" />  					
	<columnMapping excelColumn="Z"  type="char" databaseColumn="n10" /> 					
	<columnMapping excelColumn="AA" type="char" databaseColumn="certIssued" /> 			
	<columnMapping excelColumn="AB" type="char" databaseColumn="fack1" /> 				
	<columnMapping excelColumn="AC" type="date" databaseColumn="fack2" /> 				
	<columnMapping excelColumn="AD" type="char" databaseColumn="certNumber" /> 			
	<columnMapping excelColumn="AE" type="char" databaseColumn="BPVbranches" />			
	<columnMapping excelColumn="AF" type="char" databaseColumn="countryforInvoice" /> 	
	<columnMapping excelColumn="AG" type="date" databaseColumn="industry" />				
	<columnMapping excelColumn="AH" type="char" databaseColumn="internalCostLocation" />	
	<columnMapping excelColumn="AI" type="char" databaseColumn="report2018" />			
	<columnMapping excelColumn="AJ" type="char" databaseColumn="report2017" />			
</certificateSheet>
<!-- 
	finished 				date null			# "Erledi-gung"
	, vb1 					date null
    , vb2 					date null
    , vb3 					date null
    , vb4 					date null
    , manufacturer 			varchar(255)		# "Name des          Herstellers"
    , manufacturerContact 	varchar(128)		# "Anprechperson beim Hersteller"
    , manufacturerLocation 	varchar(128)		# "Produktionsstandort des Herstellers"
    , productDescription 	varchar(255)		# "Produktbeschreibung (Norm/en)"
    , auditMonthLatest 		date				# "Auditmonat spätestens"
    , checkedBy 			varchar(128)		# "PÜ-Stelle"
    , auditor 				varchar(128)		# "Auditor"
    , checkOf 				varchar(32)			# "Kontrolle der ..."
    , probeTaken 			char(1)				# "Probe-   nahme"
    , AoC 					int					# "AoC"									== laut Christ "Zahl"
    , n1  					varchar(32) null
    , n2  					varchar(32) null
    , n3  					varchar(32) null
    , n4  					varchar(32) null
    , n5  					varchar(32) null
    , n6  					varchar(32) null
    , n7  					varchar(32) null
    , n8  					varchar(32) null
    , n9  					varchar(32) null
    , n10 					varchar(32) null
    , certIssued 			date null 			# "Ausstel-lung Zertifikat"
	, fack1 				varchar(32) null	# "ÜV                   Z mit Fa."   	== Überwachungsvertrag mit Firma
    , fack2 				varchar(32) null	# "ÜV                     Z mit PÜ"  	== Überwachungsvertrag mit Prüfstelle
    , certNumber 			varchar(32) null	# "Zertifikatsnr."
    , BPVbranches			date null			# "BPV-Fachgebiete" 					== "Bauprodukteverordnung-Fachgebiete"
    , countryforInvoice 	varchar(64) null	# "Land für Faktura"
    , industry				varchar(64) null	# "Branche"
    , internalCostLocation	varchar(32) null	# "interne KST"
    , report2018			varchar(32) null	# "Bericht 2018"
    , report2017			varchar(32) null	# "Bericht 2017"
 -->
